[package]
name = "dhard"
description = "DHARD - Data structure for writing shards that persist on disk"
license = "MIT OR APACHE-2.0"
version = "0.1.0"
edition = "2024"
documentation = "https://docs.rs/dhard"
repository = "https://github.com/m-epasta/dhard"

[dependencies]
crossbeam-utils = "0.8"
parking_lot = "0.12.5"

[dev-dependencies]
criterion = "0.8"
dashmap = "6"

[[bench]]
name = "shard"
harness = false

[[bench]]
name = "map"
harness = false

[[bench]]
name = "throughput"
harness = false
