name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: extractions/setup-just@v3
      with:
        just-version: 1.58.0

    - name: clippy
      run: just cl

    - name: build
      run: cargo build --release
    - name: run tests
      run: just test
